docs/introduction.md
removed duplicate paragraph in the home page
=> fix: homepage typo

.gitignore, docs/admin/index.mdx, docs/admin/install.mdx, docs/admin/keys.mdx, docs/admin/node.mdx, docs/admin/setup.mdx, docs/admin/usage.mdx, docs/admin/validators.mdx, docs/cli/databases.md, docs/cli/installation.md, docs/daemon/_category_.json, docs/extensions/_category_.json, docs/faq.md, docs/links.mdx, docs/sdks/_category_.json
Initial `kwil-admin` docs.  Lots in the `node` command page is premature and likely to change since those features are not yet merged.
The Installation section is best guess at this point since we should probably do two things:
- publish the kwild:latest as the images created from the kwild.script.dockerfile, which will allow entering a command prompt in the docker container
- include `kwil-admin` in the binary release archives published on https://github.com/kwilteam/kwil-cli/releases, at least until we open source the kwil-db repo
=> kwil-admin docs

docs/sdks/js-ts/js-ts-apis.mdx, docs/sdks/js-ts/migration.mdx, docs/sdks/js-ts/overview.mdx
Adds `.description()` method to builders, which can be used to customize signature messages sent to both the broadcast endpoint and the call endpoint.
=> Add documentation for friendly signatures in JS SDK

.firebaserc, docs/sdks/js-ts/overview.mdx
- Added back in optional configs for kwiljs (re #37)
- Added prerelease-docs projects to firebase config for pre-release deployments
closes #37
=> js optional config + add pre-release project

docs/node/admin/kwil-admin/setup/peer.mdx
This updates the `kwil-admin` reference for the `pex`/`seeds`/`seed-mode` config changes in https://github.com/kwilteam/kwil-db/commit/566c6630e4ec4b7de1bf3fb55204d3fd6cc0ea79
=> admin: update reference for pex/seeds/seed-mode settings

README.md, docs/introduction.md, docs/node/daemon/config/settings.mdx, docs/node/daemon/install.mdx, docs/node/daemon/kwild.mdx, docs/node/quickstart.mdx, docs/node/tutorial.mdx
Mainly the Node Installation page.  I have a feeling this is TMI, but I wanted to be complete.  We could make a separate "Advanced PostgreSQL Setup" page for all the options, and just leave the one simple one (the one `postgres` Docker Compose) to the Installation page to keep it simple and not too intimidating.
=> postgresql updates to Node Installation

docs/node/network-migration.mdx
Add a few commands to help smooth the tutorial devex. Make it clear that the private_key(s) for the validator sets need to be copied.
=> add cp commands + private_key info

docs/node/daemon/config/settings.mdx
I noticed that our docs had an incorrect default pg host.
=> fixed default docs

docs/kuneiform/sql-as-understood-by-kwil/syntax-diagrams.md
This point the diagram to v0.8 version
This need https://github.com/kwilteam/kwil-db/pull/807 to be merged
=> update kuneiform diagram to v08

docs/node/daemon/eth-deposits.mdx, docs/node/daemon/kwild.mdx, docs/node/daemon/postgres.mdx
This adds a "tip" section to the PostgreSQL docker section.
When running Docker Daemon on a server (not Docker Desktop), there is a "userland proxy" that runs by default to proxy network traffic between host and container.  This is [known](https://franckpachot.medium.com/high-cpu-usage-in-docker-proxy-with-chatty-database-application-disable-userland-proxy-415ffa064955) to have an very high CPU cost, and I always disable it.  In @charithabandi 's tests, it could be observed eating as much CPU as postgres itself.
This also changes some unrelated formatting:
- "Eth" -> "Ethereum".  In general, it should be ETH for the ticker on the unit of value, or Ethereum for the network or more broad discussions.  I picked Ethereum, but let me know if ETH is right in some contexts.
- "Kwild" -> "kwild", …
=> document important Docker Daemon config

docs/kuneiform/introduction.mdx
Adds documentation for `@foreign_caller`. https://github.com/kwilteam/kwil-db/pull/832
=> docs for foreign_caller

docs/node/daemon/config/settings.mdx
I noticed a handful of config values added in v0.8 are missing, so I am adding them here.
I also updated notes on default values per the value set here: https://github.com/kwilteam/kwil-db/blob/99ea751131a70fe027d6f0515ea1bb188e0bdd14/cmd/kwild/config/config.go#L556
=> fix: update config.toml values

docs/node/daemon/config/settings.mdx
I noticed a typo in the extension flag docs for `kwild`
=> fix: incorrect extension flag

docs/node/daemon/config/genesis.mdx
Fixes incorrect JSON being used in the `genesis.json`, as well as incorrect documentation regarding `initial_height`.
Resolves https://github.com/kwilteam/docs/issues/139
=> fix genesis documentation

docs/kuneiform/sql-as-understood-by-kwil/operators.mdx
This PR updates our operator precedence table. It is loosely based on the https://github.com/kwilteam/docs/issues/133 issue, but I decided to not add an extra column as noted in the issue, because I felt it looked weird and was more confusing than helpful.
Resolves https://github.com/kwilteam/docs/issues/133
=> updated operator precedence

docs/node/daemon/postgres.mdx, docs/node/statesync.mdx
This revises the statesync docs page:
- note about requiring the `psql` and `pg_dump` tools
- reorganize sections
- statesync -> state sync (as per cometbft plain-language docs rather than code)
- reword trusted providers desc
=> statesync: reorg and doc psql/pg_dump req

docs/node/admin/kwil-admin/index.md, docs/node/admin/kwil-admin/key/index.md, docs/node/admin/kwil-admin/migrate/approve.mdx, docs/node/admin/kwil-admin/migrate/genesis-state.mdx, docs/node/admin/kwil-admin/migrate/index.md, docs/node/admin/kwil-admin/migrate/list.mdx, docs/node/admin/kwil-admin/migrate/propose.mdx, docs/node/admin/kwil-admin/migrate/status.mdx, docs/node/admin/kwil-admin/node/index.md, docs/node/admin/kwil-admin/peers/index.md, docs/node/admin/kwil-admin/peers/list.mdx, docs/node/admin/kwil-admin/peers/remove.mdx, docs/node/admin/kwil-admin/setup/genesis-hash.mdx, docs/node/admin/kwil-admin/setup/index.md, docs/node/admin/kwil-admin/setup/init.mdx, docs/node/admin/kwil-admin/setup/peer.mdx, docs/node/admin/kwil-admin/setup/reset-state.mdx, docs/node/admin/kwil-admin/setup/reset.mdx, docs/node/admin/kwil-admin/setup/testnet.mdx, docs/node/admin/kwil-admin/snapshot/create.mdx, docs/node/admin/kwil-admin/snapshot/index.md, docs/node/admin/kwil-admin/utils/index.md, docs/node/admin/kwil-admin/validators/index.md, docs/node/admin/kwil-admin/whitelist/add.mdx, docs/node/admin/kwil-admin/whitelist/index.md, docs/node/admin/kwil-admin/whitelist/list.mdx, docs/node/admin/kwil-admin/whitelist/remove.mdx, docs/node/private-networks.mdx
Renamed `kwil-admin peers` to `kwil-admin whitelist`, as per the changes made here: https://github.com/kwilteam/kwil-db/pull/985
The large change here is due to the generated reference docs. There were some we were missing.
=> rename kwil-admin peers to kwil-admin whitelist

docs/kuneiform/sql-as-understood-by-kwil/syntax-diagrams.md
The issue: If you go https://docs.kwil.com/docs/syntax-diagrams/ and click any rule block, you'll see error, because the HTML doesn't work properly.
This changes the embedded SQL syntax diagram to kwil-db Github Page, so the html anchor works.
Note: This is a better yet not ideal solution, since we can only serve one version of the syntax.
----
To support multi versions of SQL syntax diagram, we have 2 options:
First approach is, an extra Github Action that:
- will be triggered on release branch update:
- re-generate diagram html file
- put the diagram in different folder named in version, in `docs/sql-syntax` folder
- push the changes to `main` branch
So we can have a URL point to one version, for example: https://kwilteam.github.io/kwil-db/docs/sql-syntax/v0.8/index.html
The second …
=> fix: sql syntax diagram rule not clickable

docs/cli/quickstart.mdx
Removes an incorrect `--sql` flag in the `kwil-cli` docs
=> cli: remove incorrect query flag

docs/language/05-namespaces.mdx, docs/language/07-roles.mdx
Fixes a few places where I used the term "schema" when I meant "namespace"
=> fix naming inconsistencies with schemas and namespaces

docs/node/daemon/config/settings.mdx
To keep consistent, the flags for configure extension changed to `--extensions`, update the doc here
=> update extension config flag name
