trufnetwork/kwil-docs

docs/cli/databases.md

added documentation for cli query

---

docs/kuneiform/sql-as-understood-by-kwil/aggregate-functions.md
docs/kuneiform/sql-as-understood-by-kwil/scalar-functions.md

@brennanjl - made the changes you requested:
- remove reference to SQLite_3
- update format for Aggregate Functions
LMK if there's anything else that stands out to you as extraneous from the SQLite docs.

Luis aggregate functions update

---

docs/admin/install.mdx
docs/daemon/_category_.json
docs/daemon/install.mdx
docs/kwil-cli/installation.md

- change the installation to binary instead of docker
- use same template for `kwil-cli` `kwild` `kwil-admin` installation page

replace docker installation to binary

---

docs/sdks/js-ts/code_tabs.jsx
docs/sdks/js-ts/js-ts-apis.mdx
docs/sdks/js-ts/migration.mdx
docs/sdks/js-ts/overview.mdx
docs/tutorials/hello-world-application/using-the-database.mdx

Add documentation (Kwil-JS and Hello World Tutorial) for the new builder pattern alternatives described here: https://github.com/kwilteam/kwil-js/issues/32

update kwil-js for builder pattern alternatives

---

README.md

Remove Firebase deploy / CI/CD guidance as this should be done internally by Kwil after reviewing the PR.

Update Kwil docs contribution guidelines.

---

docs/cli/installation.md
docs/cli/kwil-cli/account/balance.mdx
docs/cli/kwil-cli/account/id.mdx
docs/cli/kwil-cli/account/index.md
docs/cli/kwil-cli/account/transfer.mdx
docs/cli/kwil-cli/configure.mdx
docs/cli/kwil-cli/database/batch.mdx
docs/cli/kwil-cli/database/call.mdx
docs/cli/kwil-cli/database/deploy.mdx
docs/cli/kwil-cli/database/drop.mdx
docs/cli/kwil-cli/database/execute.mdx
docs/cli/kwil-cli/database/index.md
docs/cli/kwil-cli/database/list.mdx
docs/cli/kwil-cli/database/query.mdx
docs/cli/kwil-cli/database/read-schema.mdx
docs/cli/kwil-cli/index.md
docs/cli/kwil-cli/utils/authenticate.mdx
docs/cli/kwil-cli/utils/chain-info.mdx
docs/cli/kwil-cli/utils/index.md
docs/cli/kwil-cli/utils/ping.mdx
docs/cli/kwil-cli/utils/print-config.mdx
docs/cli/kwil-cli/utils/query-tx.mdx

updated batch, somehow one of the flags changed

updated batch

---

docs/getting-started/creating-a-database.mdx
docs/kuneiform/ddl.md
docs/kuneiform/dml.md
docs/kuneiform/introduction.mdx
docs/kuneiform/sql-as-understood-by-kwil/scalar-functions.md
docs/node/admin/install.mdx
docs/node/daemon/install.mdx
docs/node/daemon/kwild.mdx
docs/node/extensions/introduction.mdx
docs/node/extensions/kuneiform.mdx
docs/node/extensions/packages/javascript.mdx
docs/node/extensions/quickstart.mdx
docs/sdks/js-ts/js-ts-apis.mdx

Fix: link updates

---

docs/cli/kwil-cli/account/transfer.mdx
docs/cli/kwil-cli/database/batch.mdx
docs/cli/kwil-cli/database/deploy.mdx
docs/cli/kwil-cli/database/drop.mdx
docs/cli/kwil-cli/database/execute.mdx

This updates the generated kwil-cli reference docs for the changes in https://github.com/kwilteam/kwil-db/pull/449

cli: update reference for sync flag

---

docs/node/daemon/config/genesis.mdx
docs/node/extensions/oracles/Deposits.mdx

Basing off [extensions/v0.7-extensions](https://github.com/kwilteam/docs/tree/extensions/v0.7-extensions) branch,  #83 should go in first

Token deposits

---

docs/getting-started/read-access-control.mdx

Fixing missing API info for KGW advanced usage

Fix KGW Advanced usage typos

---

docs/getting-started/read-access-control.mdx

fixed typo

---

docs/sdks/go/_category_.json
docs/sdks/go/github_star.jsx
docs/sdks/go/overview.mdx
docusaurus.config.js
package-lock.json
package.json

We have had a couple teams ask about the Go SDK docs, so adding this reference here so they will be more discoverable.

And short docs for GO SDK

---

docs/extensions/consensus/01-background.mdx
docs/extensions/consensus/02-kwild.mdx
docs/extensions/consensus/03-genesis.mdx
docs/extensions/consensus/04-extension.mdx
docs/extensions/consensus/05-adhoc.mdx
docs/extensions/consensus/_category_.json
docs/extensions/consensus/comments
docs/extensions/utility-functions.mdx
docs/kuneiform/_category_.json

Basically what I want.  Just want to add an Example page

coordinated upgrade

---

docs/extensions/api-reference/common.mdx
docs/extensions/oracles/example_pt_1.mdx
docs/extensions/oracles/resolutions.mdx

Updates the oracle extension with breaking changes. @KwilLuke can you get this hosted?

updated for extension breaking changes

---

docs/node/daemon/kwild.mdx
docs/node/tutorial.mdx

resolves https://github.com/kwilteam/docs/issues/135

removed references to the app http server

---

docs/kuneiform/procedures.mdx

resolves https://github.com/kwilteam/docs/issues/125

added docs for and/or

---

docs/kuneiform/sql-as-understood-by-kwil/functions.mdx

Adds docs for the new functions in v0.9. Resolves https://github.com/kwilteam/docs/issues/129

added docs for new functions

---

docs/kuneiform/introduction.mdx

Adds new contextual vars and resolves https://github.com/kwilteam/docs/issues/137

updated contextual var documentation

---

docs/kuneiform/proxy_pattern.mdx
docs/kuneiform/sql-as-understood-by-kwil/_category_.json
docs/kuneiform/testing/_category_.json

@brennanjl - I've added a Proxy Pattern md file to the Kuneiform section of the docs. It includes the following schema upgrade proxy pattern example: https://gist.github.com/brennanjl/9a5b8cb565579296087fb1b63428338f#file-impl_1-kf
Please let me know if you think this needs additional context or information.

Proxy Pattern Section

---

docs/extensions/1-overview.mdx
docs/extensions/consensus/04-extension.mdx
docs/extensions/custom-auth/example.mdx
docs/extensions/kuneiform-precompiles/example.mdx
docs/extensions/oracles/example_pt_1.mdx
docs/extensions/oracles/example_pt_2.mdx

fix broken links

---

docs/node/daemon/config/settings.mdx

Resolves https://github.com/kwilteam/docs/issues/151

tls_{cert,key}_file -> admin_tls_{cert,key}_file

---

docs/kuneiform/sql-as-understood-by-kwil/functions.mdx

document array_agg

---

docs/cli/kwil-cli/database/drop.mdx
docs/cli/kwil-cli/utils/test.mdx
docs/extensions/kuneiform-precompiles/precompiles.mdx
docs/extensions/oracles/example_pt_2.mdx
docs/kuneiform/ddl.md
docs/kuneiform/procedures.mdx
docs/kuneiform/sql-as-understood-by-kwil/functions.mdx
docs/node/production-guide.mdx
docs/sdks/go/overview.mdx
docs/sdks/js-ts/js-ts-apis.mdx

**Description**
This pull request fixes typographical errors
**Additional context**
These changes ensure correct usage and understanding of sentences and their content, which improves readability, accuracy, and quality.

Update Kwil Docs

---

docs/language/02-indexes.mdx

fix create index syntax

---

docs/bridge/00-introduction.mdx
docs/bridge/02-usage.mdx
docs/bridge/03-reference.mdx

this pr adds access modifiers to erc20-bridge methods

erc20-bridge: add access modifiers

---

docs/node/reference/print-config.mdx
docs/node/reference/setup/init.mdx
docs/node/reference/start.mdx

This is due the changes in kwilteam/kwil-db#1438

config: use log section

---

docs/getting-started/creating-a-table.mdx
docs/language/05-namespaces.mdx
docs/language/sql-reference/functions.mdx
docs/language/sql-reference/operators.mdx

Resolves:
- https://github.com/kwilteam/docs/issues/185
- https://github.com/kwilteam/docs/issues/182
- https://github.com/kwilteam/docs/issues/169

add documentation for new language features

---

docs/language/sql-reference/syntax-diagrams.md

This resolves #179.
MERGE NOTE: merge kwilteam/kwil-db#1411 first

v0.10.0 sql lang diagram

---

docs/language/sql-reference/functions.mdx

Adds new scalar functions documentation

add documentation for new functions

---

docs/language/04-actions.mdx
docs/language/08-extensions.mdx

Fixes a few typos in the language section

fix language typos

---

docs/bridge/01-setup.mdx

minor bridge documentation updates
